//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EosKadriLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CADRE_VIEW_FIO
    {
        public string ISN_FIO { get; set; }
        public string ISN_PERSON { get; set; }
        public string FIO_SHORT { get; set; }
        public string FIO { get; set; }
    }
}
