//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EosKadriLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CADRE_VIEW_PERSONSL2
    {
        public string ISN_PERSON { get; set; }
        public Nullable<decimal> PWORK { get; set; }
        public string FIO { get; set; }
        public string DOL { get; set; }
        public string ORG { get; set; }
        public string IORG { get; set; }
        public string ISN_WORK { get; set; }
        public string ISN_DISPLACEMENT { get; set; }
        public string ISN_POD { get; set; }
        public string POD { get; set; }
    }
}
