//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EosKadriLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CADRE_VIEW_RESERVE
    {
        public string ISN_RESERVE { get; set; }
        public string ISN_PERSON { get; set; }
        public string ISN_ORGANIZATION_CL { get; set; }
        public int INNER_OUTER { get; set; }
        public string PODR_NAME { get; set; }
        public string OFFICE { get; set; }
    }
}
