//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EosKadriLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class K092Context : DbContext
    {
        public K092Context()
            : base("name=K092Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CADRE_VIEW_PERSONSL> CADRE_VIEW_PERSONSL { get; set; }
        public virtual DbSet<CADRE_VIEW_PERSONSL2> CADRE_VIEW_PERSONSL2 { get; set; }
        public virtual DbSet<CADRE_VIEW_RESERVE> CADRE_VIEW_RESERVE { get; set; }
        public virtual DbSet<CADRE_VIEW_FIO> CADRE_VIEW_FIO { get; set; }
    }
}
